-- ============================================================================
-- Prövning.se — Migration 002: Curriculum varianter (per a/b/c)
-- Auto-generated from resources/curriculum/data/*.json (do not edit manually)
-- ============================================================================

BEGIN;

-- 1. Variant-kolumn på båda tabellerna
ALTER TABLE public.central_content
  ADD COLUMN IF NOT EXISTS variant CHAR(1) CHECK (variant IN ('a', 'b', 'c'));
ALTER TABLE public.knowledge_requirements
  ADD COLUMN IF NOT EXISTS variant CHAR(1) CHECK (variant IN ('a', 'b', 'c'));
CREATE INDEX IF NOT EXISTS idx_cc_level_variant ON public.central_content(level_id, variant);
CREATE INDEX IF NOT EXISTS idx_kr_level_variant ON public.knowledge_requirements(level_id, variant);

-- 2. Rensa befintliga rader (vi seedar om allt per variant)
DELETE FROM public.central_content;
DELETE FROM public.knowledge_requirements;

-- ── MATMAT01a (variant=a, level=matematik-1) ─────────────
-- Centralt innehåll: 20 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Matematiska begrepp som är relevanta för karaktärsämnen och yrkesliv, till exempel proportionalitet, skala, Pythagoras sats, procent och andelar, indexmått, vinstmarginal, jämvikt, felmarginaler, symmetrier, vektorer, trigonometriska funktioner och matematiska begrepp som utvecklas under förskoleåldern.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Beräkningsmetoder som är relevanta för karaktärsämnen och yrkesliv, till exempel uppskattningar, beräkningar på störningar eller mätfel, spill- och svinnberäkningar, överslagsräkning, avrundning, användning av kalkylprogram och metoder för kontrollberäkning.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Hantering av formler som är relevanta för karaktärsämnen och yrkesliv.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Mätning och hantering av storheter och enheter som är relevanta för karaktärsämnen och yrkesliv, till exempel enhetsbyten, avrundningsprinciper, tidsuppskattningar, beräkning av förbrukningsmaterial, kostnadsberäkningar, säkerhetsmarginaler, hantering av mätverktyg och hantering av mätosäkerheter.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Hjälpmedel och verktyg som är relevanta för att hantera matematik inom karaktärsämnen och yrkesliv, till exempel formulär, mallar, tumregler, föreskrifter, manualer, referensverk och handböcker.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Hantering av algebraiska uttryck, inklusive att faktorisera och multiplicera uttryck.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Begreppet funktion. Representationer av funktioner i form av ord, funktionsuttryck, tabeller och grafer. Digitala metoder för att skapa funktionsgrafer.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Metoder för att bestämma funktionsvärden. Grafiska metoder för att lösa ekvationer av typen f(x) = a.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Begreppet linjär funktion och egenskaper hos linjära funktioner.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Metoder för att lösa linjära ekvationer.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Begreppet exponentialfunktion och egenskaper hos exponentialfunktioner, inklusive skillnader och likheter med linjära funktioner.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Begreppet förändringsfaktor och beräkning av förändringar i flera steg.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Begreppen oberoende och beroende händelse samt komplementhändelse. Metoder för att beräkna sannolikheter i flera steg, inklusive exempel från spel, risk- och säkerhetsbedömningar.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Exempel på hur några statistiska begrepp används i samhälle och yrkesliv, inklusive signifikans, korrelation, kausalitet, urvalsmetoder och felkällor.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Användning av kalkylprogram för beräkning av ränta och amortering.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Problemlösning som omfattar att upptäcka och uttrycka generella samband.', 16, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i yrkesliv, privatekonomi och samhällsliv.', 17, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 18, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 19, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'a', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT01b (variant=b, level=matematik-1) ─────────────
-- Centralt innehåll: 19 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Hantering av formler och algebraiska uttryck, inklusive att faktorisera och multiplicera uttryck.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppen funktion, definitionsmängd och värdemängd. Representationer av funktioner i form av ord, funktionsuttryck, tabeller och grafer. Digitala metoder för att skapa funktionsgrafer.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Metoder för att bestämma funktionsvärden. Digitala och grafiska metoder för att lösa ekvationer av typen f(x) = a.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppet linjär funktion och egenskaper hos linjära funktioner. Räta linjens ekvation. Metoder för att bestämma linjära funktioner.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Metoder för att lösa linjära ekvationer.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppen intervall och linjär olikhet. Metoder för att lösa linjära olikheter.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppet exponentialfunktion och egenskaper hos exponentialfunktioner, inklusive skillnader och likheter med linjära funktioner.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Motivering och hantering av räkneregler för potenser. Metoder för att lösa potensekvationer.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppet potensfunktion.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppet förändringsfaktor och beräkning av förändringar i flera steg.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppet index.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Begreppen oberoende och beroende händelse samt komplementhändelse. Metoder för att beräkna sannolikheter i flera steg, inklusive exempel från spel, risk- och säkerhetsbedömningar.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Exempel på hur några statistiska begrepp används i samhälle och inom vetenskap, inklusive signifikans, korrelation, kausalitet, urvalsmetoder och felkällor.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Användning av kalkylprogram för beräkning av ränta och amortering.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Problemlösning som omfattar att upptäcka och uttrycka generella samband.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen, privatekonomi och samhällsliv.', 16, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 17, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 18, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'b', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT01c (variant=c, level=matematik-1) ─────────────
-- Centralt innehåll: 21 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Hantering av formler och algebraiska uttryck, inklusive att faktorisera och multiplicera uttryck.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppen funktion, definitionsmängd och värdemängd. Representationer av funktioner i form av ord, funktionsuttryck, tabeller och grafer. Digitala metoder för att skapa funktionsgrafer.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Metoder för att bestämma funktionsvärden. Digitala och grafiska metoder för att lösa ekvationer av typen f(x) = a.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppet linjär funktion och egenskaper hos linjära funktioner. Räta linjens ekvation. Metoder för att bestämma linjära funktioner.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Metoder för att lösa linjära ekvationer.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppen intervall och linjär olikhet. Metoder för att lösa linjära olikheter.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppet exponentialfunktion och egenskaper hos exponentialfunktioner, inklusive skillnader och likheter med linjära funktioner.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Motivering och hantering av räkneregler för potenser. Metoder för att lösa potensekvationer.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppet potensfunktion.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppet förändringsfaktor och beräkning av förändringar i flera steg.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppen sinus, cosinus och tangens. Begreppet invers funktion i samband med arcusfunktioner. Metoder för att beräkna sträckor och vinklar i koordinatsystem och i rätvinkliga trianglar.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppet vektor. Representationer av vektorer i koordinatsystem och skrivna i koordinatform. Metoder för beräkningar med vektorer, inklusive addition, subtraktion, beräkning av absolutbelopp och multiplikation med skalär.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Begreppen oberoende och beroende händelse samt komplementhändelse. Metoder för att beräkna sannolikheter i flera steg, inklusive exempel från spel, risk- och säkerhetsbedömningar.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Exempel på hur några statistiska begrepp används i samhälle och inom vetenskap, inklusive signifikans, korrelation, kausalitet, urvalsmetoder och felkällor.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Användning av kalkylprogram för beräkning av ränta och amortering.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Problemlösning som omfattar att upptäcka och uttrycka generella samband.', 16, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen, privatekonomi och samhällsliv.', 17, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Exempel på hur programmering kan användas som verktyg vid problemlösning, databearbetning eller tillämpning av numeriska metoder.', 18, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 19, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 20, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-1'), 'c', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT02a (variant=a, level=matematik-2) ─────────────
-- Centralt innehåll: 17 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Breddning eller fördjupning av matematiska begrepp och metoder som är relevanta för karaktärsämnen och yrkesliv.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Hjälpmedel och verktyg som är relevanta för att hantera matematik inom karaktärsämnen och yrkesliv.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Räta linjens ekvation. Metoder för att bestämma linjära funktioner.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Begreppet linjärt ekvationssystem. Metoder för att lösa linjära ekvationssystem.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Begreppet potensfunktion.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Motivering och hantering av räkneregler för potenser. Metoder för att lösa potensekvationer.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Digitala metoder för att lösa exponentialekvationer.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Motivering och hantering av konjugat- och kvadreringsreglerna.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Begreppet andragradsfunktion och egenskaper hos andragradsfunktioner, inklusive symmetrilinje, extrempunkt och nollställen.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Metoder för att lösa andragradsekvationer.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Lägesmått och spridningsmått, inklusive percentiler och standardavvikelse, samt digitala metoder för att bestämma dessa.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Begreppet normalfördelning och egenskaper hos normalfördelat material. Metoder för att göra enklare beräkningar på normalfördelat material.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Användning och motivering av Pythagoras sats, inklusive exempel som omfattar beräkningar i koordinatsystem.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i yrkes- och samhällsliv.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 16, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'a', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT02b (variant=b, level=matematik-2) ─────────────
-- Centralt innehåll: 16 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppet linjärt ekvationssystem. Metoder för att lösa linjära ekvationssystem.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppet logaritm. Hantering av räkneregler för logaritmer i samband med lösning av exponentialekvationer. Metoder för att lösa exponentialekvationer.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Likheter och skillnader mellan exponential- och potensekvationer.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Motivering och hantering av konjugat- och kvadreringsreglerna.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppet andragradsfunktion och egenskaper hos andragradsfunktioner, inklusive symmetrilinje, extrempunkt och nollställen.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Metoder för att lösa andragradsekvationer.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Lägesmått och spridningsmått, inklusive percentiler och standardavvikelse, samt digitala metoder för att bestämma dessa.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppet normalfördelning och egenskaper hos normalfördelat material. Digitala metoder för att göra beräkningar på normalfördelat material.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppen regressionsanalys och korrelationskoefficient. Digitala metoder för regressionsanalys.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppen implikation och ekvivalens.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Begreppen definition, sats och bevis.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Användning och motivering av grundläggande klassiska satser i geometri om vinklar och likformighet samt Pythagoras sats, inklusive exempel som omfattar beräkningar i koordinatsystem.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen och samhällsliv.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 15, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'b', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT02c (variant=c, level=matematik-2) ─────────────
-- Centralt innehåll: 18 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppet linjärt ekvationssystem. Metoder för att lösa linjära ekvationssystem.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppet logaritm. Motivering och hantering av räkneregler för logaritmer. Metoder för att lösa exponentialekvationer.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Likheter och skillnader mellan exponential- och potensekvationer.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Motivering och hantering av konjugat- och kvadreringsreglerna.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppet andragradsfunktion och egenskaper hos andragradsfunktioner, inklusive symmetrilinje, extrempunkt och nollställen.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Metoder för att lösa andragradsekvationer.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Metoder för att lösa rotekvationer.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Lägesmått och spridningsmått, inklusive percentiler och standardavvikelse, samt digitala metoder för att bestämma dessa.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppet normalfördelning och egenskaper hos normalfördelat material. Digitala metoder för att göra beräkningar på normalfördelat material.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppen regressionsanalys och korrelationskoefficient. Digitala metoder för regressionsanalys.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppen implikation och ekvivalens.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Begreppen definition, sats och bevis.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Användning och motivering av grundläggande klassiska satser i geometri om vinklar och likformighet samt Pythagoras sats, inklusive exempel som omfattar beräkningar i koordinatsystem.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Användning av digitala verktyg för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen och samhällsliv.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Exempel på hur programmering kan användas som verktyg vid problemlösning, databearbetning eller tillämpning av numeriska metoder.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 16, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 17, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter. Eleven för relativt väl underbyggda matematiska resonemang och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-2'), 'c', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter. Eleven för väl underbyggda matematiska resonemang och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT03b (variant=b, level=matematik-3) ─────────────
-- Centralt innehåll: 16 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppet rationella uttryck. Hantering av rationella uttryck.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppet gränsvärde. Begreppen sekant, tangent, förändringshastighet, ändringskvot och derivata för en funktion. Grafiska och digitala metoder för att derivera funktioner. Villkor för deriverbarhet.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Motivering och hantering av deriveringsregler för potens- och exponentialfunktioner samt summor av dessa. Begreppen talet e och naturlig logaritm.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppet andraderivata. Metoder för att lösa extremvärdesproblem.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppet polynom och egenskaper hos polynomfunktioner. Metoder för att lösa enklare polynomekvationer.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppen primitiv funktion och bestämd integral. Sambandet mellan primitiv funktion och derivata.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Grafiska och digitala metoder för att bestämma integraler.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Motivering och hantering av metoder för att bestämma integraler för potens- och exponentialfunktioner samt summor av dessa.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Formulering och beräkning av integraler i enkla situationer.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Metoder för linjär optimering.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Begreppet geometrisk summa. Metoder för att bestämma geometriska summor.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Användning av digitala verktyg, även symbolhanterande, för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning, derivering, integrering och hantering av algebraiska uttryck.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen och samhällsliv.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Användning av programmering som verktyg vid problemlösning, databearbetning eller tillämpning av numeriska metoder.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 15, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven hanterar avancerade uttryck med god säkerhet. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för relativt väl underbyggda matematiska resonemang , genomför enkla bevis och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'b', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven hanterar avancerade uttryck med mycket god säkerhet. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för väl underbyggda matematiska resonemang , genomför bevis och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt. <a', 2);

-- ── MATMAT03c (variant=c, level=matematik-3) ─────────────
-- Centralt innehåll: 17 punkter
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet absolutbelopp.', 0, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet rationella uttryck. Hantering av rationella uttryck.', 1, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet gränsvärde. Begreppen sekant, tangent, förändringshastighet, ändringskvot och derivata för en funktion. Grafiska och digitala metoder för att derivera funktioner. Villkor för deriverbarhet.', 2, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Motivering och hantering av deriveringsregler för potens- och exponentialfunktioner samt summor av dessa. Begreppen talet e och naturlig logaritm.', 3, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet andraderivata. Metoder för att lösa extremvärdesproblem.', 4, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet polynom och egenskaper hos polynomfunktioner. Metoder för att lösa enklare polynomekvationer.', 5, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppen primitiv funktion och bestämd integral. Sambandet mellan primitiv funktion och derivata.', 6, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Grafiska och digitala metoder för att bestämma integraler.', 7, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Motivering och hantering av metoder för att bestämma integraler för potens- och exponentialfunktioner samt summor av dessa.', 8, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Formulering och beräkning av integraler i enkla situationer.', 9, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Begreppet enhetscirkeln. Definition av trigonometriska begrepp utifrån enhetscirkeln.', 10, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Bevis och användning av cosinus-, sinus- och areasatsen.', 11, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Användning av digitala verktyg, även symbolhanterande, för att effektivisera beräkningar och komplettera metoder, till exempel vid ekvationslösning, derivering, integrering och hantering av algebraiska uttryck.', 12, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Problemlösning som omfattar begrepp och metoder i kursen, med särskild utgångspunkt i karaktärsämnen och samhällsliv.', 13, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Användning av programmering som verktyg vid problemlösning, databearbetning eller tillämpning av numeriska metoder.', 14, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Tillämpning och formulering av matematiska modeller i realistiska situationer. Utvärdering av matematiska modellers egenskaper och begränsningar.', 15, '2025-skolverket');
INSERT INTO public.central_content (level_id, variant, content, order_index, version) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'Matematiska problem med anknytning till matematikens kulturhistoria.', 16, '2025-skolverket');
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'E', 'Eleven beskriver grundläggande begrepp och samband mellan begrepp samt använder dem med tillfredsställande säkerhet. Eleven hanterar grundläggande procedurer och löser uppgifter av standardkaraktär med tillfredsställande säkerhet, både utan och med digitala verktyg. Eleven löser enkla problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i enkla uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för delvis underbyggda matematiska resonemang och följer enkla matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett i huvudsak fungerande sätt.', 0);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'C', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med god säkerhet, både utan och med digitala verktyg. Eleven hanterar avancerade uttryck med god säkerhet. Eleven löser relativt komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i relativt komplexa uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för relativt väl underbyggda matematiska resonemang , genomför enkla bevis och följer relativt avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett till stor del tydligt och korrekt sätt.', 1);
INSERT INTO public.knowledge_requirements (level_id, variant, grade_level, description, order_index) VALUES ((SELECT id FROM public.levels WHERE slug = 'matematik-3'), 'c', 'A', 'Eleven beskriver ett omfattande antal begrepp och samband mellan begrepp samt använder dem med mycket god säkerhet. Eleven hanterar ett omfattande antal procedurer och löser uppgifter av standardkaraktär med mycket god säkerhet, både utan och med digitala verktyg. Eleven hanterar avancerade uttryck med mycket god säkerhet. Eleven löser komplexa problem inom kursens olika områden. Eleven bedömer resultatens rimlighet. Eleven tillämpar och formulerar matematiska modeller i komplexa uppgifter, samt utvärderar matematiska modellers egenskaper och begränsningar. Eleven för väl underbyggda matematiska resonemang , genomför bevis och följer avancerade matematiska resonemang. Eleven uttrycker sig med matematiska symboler och andra representationer på ett tydligt och korrekt sätt.', 2);

-- 3. Verifiering
DO $$
DECLARE
  cc_count INT;
  kr_count INT;
BEGIN
  SELECT COUNT(*) INTO cc_count FROM public.central_content;
  SELECT COUNT(*) INTO kr_count FROM public.knowledge_requirements;
  RAISE NOTICE 'Centralt innehåll: % rader (förväntat 144)', cc_count;
  RAISE NOTICE 'Kunskapskrav: % rader (förväntat 24)', kr_count;
END $$;

COMMIT;
